### ISSUE TITLE
Please use an open source/free software license

### ISSUE THREAD

**Issue by TrashMacNugget** [kori/Xlambda#3]
A few days ago the license was changed to the Parity Public License. As far as I can tell, this license is neither "open source" nor "free software", and has not been approved under the FSF, OSI, or DFSG. As far as I can tell, under widely accepted definitions it is "non-free".

It violates freedom 0 of the FSF's Free Software definition, "the freedom to run the program as you wish, for any purpose", by not allowing local private modifications, with clauses #1, #2, and #3 in direct violation.

It also appears to be incompatible with the Open Source Definition/Debian Free Software Guidelines, clause #6, but I'm not entirely sure on that.

Would you consider using a license that is free and open source? If you like copyleft some flavor of GPL would be good, or if you want something permissive MIT or Apache 2 are solid choices.

**Comment by ghost** [comment]
I highly encourage this too.

**Comment by luizdemilon** [comment]
Thanks for opening this issue!

I should clarify that the license was not changed to the Parity Public License, but instead, any code written **after** commit 8af38ef59496889dc2bbbc7d43ebc888a055465b (i.e. when I started commiting code) is licensed under Parity.

I should also note I have no issue with the GPLv3 or the ISC (my preferred permissive license of choice). All my other projects are under either license.

I am aware that this license is not approved by the FSF, or OSI, or DFSG, but that's fine by me. The restrictions upon its usage and distributions, as they break clause 6 of the OSD/DFSG, are also desireable to me. I have no intention of letting Xlambda's code be closed off in any case, for any reason.

Another reason why I have not picked the GPLv3 or the ISC for this project is that I also want to display these sorts of ideas to a wider audience (As far as I know, there are not many projects utilizing Parity. A Github search returns a few, but not many).

I'd like to hear any further thoughts on this, considering my position.

Thanks again!

**Comment by TrashMacNugget** [comment]
> The restrictions upon its usage and distributions, as they break clause 6 of the OSD/DFSG, are also desireable to me. I have no intention of letting Xlambda's code be closed off in any case, for any reason.

Under the license, it seems I am not allowed to make any changes without releasing them. This essentially means any configuration/scripting I do, I must release. For a window manager this is an absurd requirement.

Given the scope and target audience of Xlambda, it is extremely unlikely it would ever be closed off. You are in no danger of commercialization. I think this license will hinder adoption more than anything.

What potential for the code being closed up do you hope to prevent with this license? (I.e. what scenarios where GPL falls short are you protecting against?)

**Comment by luizdemilon** [comment]
> Under the license, it seems I am not allowed to make any changes without releasing them. **This essentially means any configuration/scripting I do, I must release.** For a window manager this is an absurd requirement.

This doesn't sound absurd to me, in fact, it sounds extremely positive. I *do*, in fact, want to see every single possible configuration out there. That's one of the projects goals, in fact, to understand what's fundamental to a window manager. Having more configurations available to study seems like it directly benefits that goal.

> I think this license will hinder adoption more than anything.

Hopefully not, and hopefully the previous point will also be a positive to most people.

> Given the scope and target audience of Xlambda, it is extremely unlikely it would ever be closed off. You are in no danger of commercialization. 
> What potential for the code being closed up do you hope to prevent with this license? (I.e. what scenarios where GPL falls short are you protecting against?)

I don't think Xlambda, specifically, is at danger of being commercialized or closed, but as I said in the original post, I want to spread these ideas (and Parity) to a wider audience, and having software that could potentially be widely used (such as a window manager, as opposed to more niche software, e.g. web services with a specific purpose) is a great way to guarantee that this is spread as far as possible.

**Comment by jakub-olczyk** [comment]
For me the restriction that I **have to** share my configuration is not very exciting. I'd be much more inclined to do that if I found the software so exciting that I **want to** share my config with the world :smile: 

Since the configuration is essentially a Scheme program this restriction is quite bizarre for me. This situation sounds to me a lot like the one where someone would develop new interpreter for a language and require that all of the programs written in it have to be released in order to use the interpreter.

Plus, I think that this is very similar to the original Emacs problems. And I'd say that in this particular case better solution would be to use GPLv3, just like the devs of Emacs did. Plus, release sample configuration as GPLv3 code, this will be a starting point where the changes would need to be contributed back to the project if someone where to create their own distribution of Xlambda.

Cheers!

**Comment by luizdemilon** [comment]
> **For me the restriction that I **have to** share my configuration is not very exciting.** I'd be much more inclined to do that if I found the software so exciting that I **want to** share my config with the world
> **Since the configuration is essentially a Scheme program this restriction is quite bizarre for me.** 

I understand and I politely disagree. I think this is a fine restriction. 

>This situation sounds to me a lot like the one where someone would develop new interpreter for a language and require that all of the programs written in it have to be released in order to use the interpreter.

Again, this seems good to me, for Xlambda's specific case.

I'm closing this issue since it seems to me that all the points have been addressed.

Thanks!
