### ISSUE TITLE
Wording of license

### ISSUE THREAD

**Issue by moon-chilled** [kori/Xlambda#5]
Hi.  There's currently an open issue to change the license (FWIW I recommend BSD-2); I'll let you deal with that as you wish, but as is I have some recommendations to change the wording of the license.  Specifically:

- "This license lets you use and share this software for free, as long as you contribute software you make with it. Specifically" - this could be read as saying that this is the *only* constraint, and the rest of the license is simply clarifying; which isn't true.  I might say "...as long as you abide by certain conditions.  These are:"

- "If you follow the rules below, you may do everything with this software that would otherwise infringe either the contributor's copyright in it, any patent claim the contributor can license, or both" - This part is overly wordy, IMO, and could in theory exclude some activities your users might want to do.  I would just say "You may deal in this software without restriction, so long as you abide by the following rules:"

- All the rules should be in the second person, so e.g. 'you must contribute changes and additions...' instead of just 'contribute changes and additions'.

- Put definitions before everything else, so they can't accidentally be mistaken for terms.  That is, put a section right after the copyright line, saying 'definitions: Software: all source and binary files and other associated works of [... whatever]; Source code: preferred form for modifying the software; Contribute: make available..."   Make it very clear that you are *defining* the term 'contribute' to mean what you want it to mean, otherwise it could be twisted.

- The second-to-last line has a number of confusing and ambiguous sections.  'unknowingly breaking 1, 2, or 3' should be 'unknowingly breaking rules 1, 2, or 3'.  Also take out unknowingly; it's very hard, legally, to prove knowledge.  Similarly, at the end you should say 'within 30 days of being informed you broke the license terms'.  Also 'stop doing anything requiring this license' is really vague; you don't need a license to *do* anything!  I'm honestly not sure what you meant by that; maybe just take it out entirely?

And by the way, this is the reason you should really just switch to a standard license like BSD or Apache.  I'm not a lawyer, and I already found a list of problems longer than the license itself :P

- Oh, also, you need to pluralise everywhere it says 'contributor' because I contributed :)

**Comment by luizdemilon** [comment]
Thanks for opening this issue!

As I was not the one who drafted this license, I will forward this issue to License Zero's repo, and I hope they reply.

This issue will stay open to track this.

Link to the issue at licensezero: https://github.com/licensezero/parity-public-license/issues/50

**Comment by luizdemilon** [comment]
There was a reply, suggesting you forward questions to that issue. I'm going to close this for now, then.
