### ISSUE TITLE
Use Liberapay to receive donations?

### ISSUE THREAD

**Issue by ghost** [kori/Xlambda#6]
Liberapay (https://en.liberapay.com/) is the free software friendly alternative to Patreon. You may use both, but some people will actively not donate because of a lack of an ethical medium.

I personally am looking to contribute both time and money to this project if it is both licensed under an FSF-approved license (https://github.com/kori/Xlambda/issues/3) and is available on Liberapay.

Until both of those conditions are met, I unfortunately can not do anything to help.

**Comment by luizdemilon** [comment]
I will create a Liberapay account, however, note reply https://github.com/kori/Xlambda/issues/3#issuecomment-508560621 on Licensing.

I am waiting for License Zero's reply on this issue: https://github.com/licensezero/parity-public-license/issues/50, if this interests you.

**Comment by luizdemilon** [comment]
I created a liberapay account: https://en.liberapay.com/kori/
