### ISSUE TITLE
Relicense under GPLv3

### ISSUE THREAD

**Issue by luizdemilon** [kori/Xlambda#7]
I've decided to relicense Xlambda's code under GPLv3.

@fheee, besides me, you're the only under that contributed code under Parity, at 2f513ba47ff7d8bbcde301ed52117d41ec80ac82.

Do I have your permission to relicense that code under GPLv3?

**Comment by ghost** [comment]
> I've decided to relicense Xlambda's code under GPLv3.
> 
> @fheee, besides me, you're the only under that contributed code under Parity, at [2f513ba](https://github.com/kori/Xlambda/commit/2f513ba47ff7d8bbcde301ed52117d41ec80ac82).
> 
> Do I have your permission to relicense that code under GPLv3?

Thank you for making this decision. I find it to be a very wise choice. I look forward to contributing to further releases.

**Comment by luizdemilon** [comment]
@brettgilio I'm glad you're looking to contribute.

I'm just waiting on @fheee's response in order to continue.

**Comment by luizdemilon** [comment]
As of commit https://github.com/kori/Xlambda/commit/af330ca312dd38e17fe1a66ed3bb68f968eaaa63, @fheee's contribution was removed, so I'm moving forward with the relicensing.
